### ISSUE TITLE
Monitoring multiple metrics

### ISSUE THREAD

**Issue by fblundun** [awslabs/amazon-kinesis-scaling-utils#14]
Hey Ian, it looks like amazon-kinesis-scaling-utils lets you autoscale based on either `PUT` or `GET` throughput, but not both at once. Is that correct?

It would be nice to be able to autoscale based on the maximum of the two metrics. We are happy to work on this feature!

**Comment by IanMeyers** [comment]
Hi Fred - that's right - today we only monitor either the GetRecords metric, or both the PutRecord and PutRecords metrics. Very very happy to review and accept a pull request for a combined capability. Would be awesome!

**Comment by IanMeyers** [comment]
So it only took a year, but version .9.5.0-beta-1 now was support for monitoring PUT and GET at the same time. Would love to have feedback on this new version.
