### ISSUE TITLE
Option for min number of shards

### ISSUE THREAD

**Issue by ankurmitujjain** [awslabs/amazon-kinesis-scaling-utils#16]
If the stream is quiet than application will reduce the shard to 1. But if a sudden data burst occurs (2-3 MB/sec) than stream with 1 shard will not be able to handle it resulting in lot of failed req, so there should be an option for min number of shard that need to be maintained always

**Comment by IanMeyers** [comment]
Yep - good suggestion - I will add this in the next release (.9.1.8+)

**Comment by IanMeyers** [comment]
Pushed .9.1.8 with support for min and max shards on scaling client and autoscaling monitor
