### ISSUE TITLE
Threshold should be a range

### ISSUE THREAD

**Issue by ankurmitujjain** [awslabs/amazon-kinesis-scaling-utils#17]
Threshold should be range instead of a single point. Otherwise stream will keep updating after coolOffMins.

**Comment by IanMeyers** [comment]
Not sure I understand the issue. Can you please provide a little more detail on what type of Threshold you mean?

**Comment by ankurmitujjain** [comment]
scaleThresholdPct

**Comment by IanMeyers** [comment]
The way that the autoscaling monitor works is to take a scale up and/or scale down configuration. If the observed metric is below the scaleThresholdPct on the scale down configuration, it will initiate the scale down using the % or count  as configured. If the observed metric is above the scaleThresholdPct on the scale up configuration, then the scale up operation will be initiated by count or %. So by having a scaleUp and scaleDown operation, you define a range outside of which scaling up or down should occur.

Does that help?

**Comment by ankurmitujjain** [comment]
Yes... this helps and should work.... Thanks
