### ISSUE TITLE
Undocumented but required configuration parameter "refreshShardsNumberAfterMin"

### ISSUE THREAD

**Issue by jpalay** [awslabs/amazon-kinesis-scaling-utils#23]
There seems to be a configuration parameter `refreshShardsNumberAfterMin` which, if not set, defaults to `null` and causes a `NullPointerException` after the daemon runs for a few minutes. However, I didn't see this in the README anywhere. This ended up biting us, so maybe this should be documented to save others the trouble? Some other things that would be helpful:

1. It'd be nice if the autoscaling daemon failed early with a helpful error message if the configuration isn't right. This would have saved us a lot of time.
2. When a `StreamMonitor` fails, it'd be helpful if it printed a stack trace to make debugging what went wrong easier. I ended up adding a line just above [here](https://github.com/awslabs/amazon-kinesis-scaling-utils/blob/fd9b0f23a1012bf474c00546ca81c8032d459a29/src/main/java/com/amazonaws/services/kinesis/scaling/auto/AutoscalingController.java#L142) to log the exception from the failed StreamMonitor, which helped me debug my issue.

Let me know what you think, thanks!
-Josh

**Comment by IanMeyers** [comment]
Hi Josh,

Apologies for this - missed that out of the documentation. Version .9.3.1 fixes this in the readme, and also adds defaults for this value (10 minutes) and for region (us-east-1).

Thanks,

Ian

**Comment by IanMeyers** [comment]
And .9.3.2 adds configuration validation of some obvious things that might be easy to miss.

**Comment by jpalay** [comment]
Awesome, thank you!
