### ISSUE TITLE
Allow for pagination of describe-stream

### ISSUE THREAD

**Issue by fblundun** [awslabs/amazon-kinesis-scaling-utils#26]
Hello @IanMeyers ,

Just noticed that the `describeStream` method executes a single DescribeStreamRequest [here](https://github.com/awslabs/amazon-kinesis-scaling-utils/blob/922e81f30d63fae6d359c21a3a3c055e280ddb7c/src/main/java/com/amazonaws/services/kinesis/scaling/StreamScalingUtils.java#L118-L140). But according to the [docs](http://docs.aws.amazon.com/cli/latest/reference/kinesis/describe-stream.html) describe-stream is a paginated operation - so is it possible that some shards could be missed?

**Comment by IanMeyers** [comment]
Sorry - and further, this specific call is for stream status, which doesn't have a dependency on the number of shards and so pagination isn't a problem.

On 2 Mar 2016, at 14:08, Fred Blundun <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello @IanMeyers<https://github.com/IanMeyers> ,

Just noticed that the describeStream method executes a single DescribeStreamRequest here<https://github.com/awslabs/amazon-kinesis-scaling-utils/blob/922e81f30d63fae6d359c21a3a3c055e280ddb7c/src/main/java/com/amazonaws/services/kinesis/scaling/StreamScalingUtils.java#L118-L140>. But according to the docs<http://docs.aws.amazon.com/cli/latest/reference/kinesis/describe-stream.html> describe-stream is a paginated operation - so is it possible that some shards could be missed?

-
Reply to this email directly or view it on GitHub<https://github.com/awslabs/amazon-kinesis-scaling-utils/issues/26>.



Amazon Web Services UK Limited. Registered in England and Wales with registration number 08650665 and which has its registered office at 60 Holborn Viaduct, London EC1A 2FD, United Kingdom.

**Comment by fblundun** [comment]
Good point! Sorry for the confusion - I'll close the issue.
