### ISSUE TITLE
Strange behaviour

### ISSUE THREAD

**Issue by zoltan-molnar** [awslabs/amazon-kinesis-scaling-utils#32]
Hi there,

I deployed it to an EB application (dist/KinesisAutoscaling-.9.4.1.war file) and I use the following config:
`[{
    "streamName": "prod-tracking",
    "region": "us-east-1",
    "scaleOnOperation": "PUT",
    "minShards": 1,
    "maxShards": 10,
    "refreshShardsNumberAfterMin": 10,
    "scaleUp": {
         "scaleThresholdPct": 20,
         "scaleAfterMins": 1,
         "scalePct": 25
     },
     "scaleDown":{
         "scaleThresholdPct": 5,
         "scaleAfterMins": 1,
         "scalePct": 20,
         "coolOffMins": 3
     }
}]`
In the log I can see that it tries to scale down (but it should scale up, because I have traffic on it), because the threshold is under 25% (which belongs to the scale up)
![screen shot 2016-04-28 at 08 10 35](https://cloud.githubusercontent.com/assets/4689364/14878105/4de94322-0d19-11e6-8b16-17f0a35e4161.png)
![screen shot 2016-04-28 at 08 10 58](https://cloud.githubusercontent.com/assets/4689364/14878112/598bc574-0d19-11e6-8f5e-db1a9265224a.png)

What am I missing? Why is it not scaling up?

**Comment by IanMeyers** [comment]
Hello,

This looks as expected, as the PUT counts are very very low. You are consuming 2.6K of a stream which can accomodate 1MB/Shard, and so the % rates are correspondingly low - in your screen shot it shows samples of .37%, .26%, .4%, .21% and so on - mind these are less than 1%, not .37% = 37%. As these all fall below your 5% scale down limit the scaler is trying to reduce capacity. The graph above certainly suggests higher PUT throughput, but don't see that in the logs.

Happy to investigate further though.

Thx,

Ian

**Comment by zoltan-molnar** [comment]
I'm consuming ~200kB put on one shard here (left axis) with ~ 260 records (right axis). So it should be definitely more than 1%.

And I also want to scale by number of put records because, there is a limit in Kinesis for put records (1000/sec) and my avg record size is less than 1KB so, I will hit this limit before I hit the 1MB limit. can I do that?

**Comment by IanMeyers** [comment]
The PUT operation is checked on record count and in total bytes, so that should all be as expected. 

As for the PUT rate, does it appear that the metrics are incorrect for your stream?

**Comment by az3** [comment]
1 Shard gives you 1.000 PUT per second, so it makes 60.000 per minute.
Your application uses 200 per minute. 
200/60000 = 0.33% usage for record put limit.

1 Shard gives you 1 MB per second, so it makes 60 MB per minute, but your application sends 200KB per minute. That is also less than 1% of a single shards limit.

**Comment by zoltan-molnar** [comment]
No, we have this kind of put record to this stream, and this is the only stream we use, so it should be right. That's why I was confused, because I know that we have ~200-600 put records with ~651bytes avg size, so it should have scale up with a 20% threshold.
Can be something because I already have traffic on this stream? It shouldn't be a problem, should it?

Thanks for helping figuring out

**Comment by zoltan-molnar** [comment]
ohh, sorry sec/minutes. that's true.
