### ISSUE TITLE
Suppress SNS notification when min/max prevents reshard?

### ISSUE THREAD

**Issue by pgieser** [awslabs/amazon-kinesis-scaling-utils#35]
It would be nice to have SNS notifications suppressed if the UP/DOWN decision is aborted because the number of shards as already at the min/max value.

**Comment by IanMeyers** [comment]
Hello,

Thanks for the feature request - version .9.5.1-beta-1 now has a new metric which is sent with the notification - "endStatus', which can be one of:

```ReportOnly, NoActionRequired, AlreadyAtMinimum, AlreadyAtMaximum, Error, Ok```

If the scaler is already and min or max you will see ```AlreadyAtMinimum``` or ```AlreadyAtMaximum```, and so can filter out these from your monitoring solution. While this isn't suppressing the notification, it should be adequate to allow you to filter alarms.

Feedback welcome.

Ian

**Comment by pgieser** [comment]
Thanks for the quick turnaround!

Unless I am misunderstanding something, there appears to be no mechanism for the fields in `ScalingOperationReport` to be propagated to the SNS notification.  It looks like the message for the notification is from `report.asJson()` which only includes the shard map.

**Comment by IanMeyers** [comment]
Right you are - sorry - fixed - you now get the whole report object in the JSON format
