### ISSUE TITLE
Question about minumum shards to resize on pct

### ISSUE THREAD

**Issue by geisbruch** [awslabs/amazon-kinesis-scaling-utils#4]
Hi,
Does the Auto-Process has some minimum of shards to split when you set scale Pct? For example if I have an stream that should be scaled and this stream has 2 shards and have specified 15% in scalePct a new hard will be added ?

Thanks, 
Gabriel.

**Comment by IanMeyers** [comment]
Yes, we err on the side of acting when you've said you want to scale, even if that's by a small amount. This is applied on both manual and autoscaling. The percent calculation is as follows:

        int newSize = new Double(Math.ceil(currentSize + (currentSize * byPct))).intValue();

Hope that helps!

Ian
