### ISSUE TITLE
WAR link 404

### ISSUE THREAD

**Issue by clovervalleyapps** [awslabs/amazon-kinesis-scaling-utils#44]
Hello. Thank you for your fine work. FYI. The following link results in a 404 error:

"Deploy the WAR by uploading from your local GitHub copy of dist/KinesisAutoscaling.war."
https://github.com/awslabs/amazon-kinesis-scaling-utils/blob/master/dist/KinesisAutoscaling.war

**Comment by IanMeyers** [comment]
Thanks for catching that. Fixed in https://github.com/awslabs/amazon-kinesis-scaling-utils/commit/959fec15ea9bcf6e8bb0c77bf31161dfc7d04d26.
