### ISSUE TITLE
Can only monitor 20 streams

### ISSUE THREAD

**Issue by pgieser** [awslabs/amazon-kinesis-scaling-utils#45]
I've observed that of the 26 streams we have configured to be monitored, only 20 are actually monitored. 

This appears to be a consequence of the fixed thread pool of 20 initialized in `AutoscalingController`.  Since each stream monitor consumes a thread for the lifetime of the app, 6 streams never get a thread.

**Comment by IanMeyers** [comment]
Yeah. Sorry about that. Have a crack with .9.5.2 and see if that fixes the issue. You will now get a thread per-stream that you configure in the config-file.

**Comment by pgieser** [comment]
Looks good!
