### ISSUE TITLE
The security token included in the request is invalid.

### ISSUE THREAD

**Issue by lexicalunit** [awslabs/amazon-kinesis-scaling-utils#5]
How are security tokens configured when using the CLI? I have tokens for profiles configured in my `~/.aws/config` file, but I don't see how I supply to the CLI which token it should be using.

```
$ java -cp KinesisScalingUtils.jar-complete.jar -Dstream-name=mytest -Dscaling-action=scaleUp -Dcount=5 -Dregion=us-east-1 ScalingClient
Exception in thread "main" com.amazonaws.AmazonServiceException: The security token included in the request is invalid. (Service: AmazonKinesis; Status Code: 400; Error Code: UnrecognizedClientException; Request ID: UUID-OMIT)
	at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1078)
	at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:726)
	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:461)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:296)
	at com.amazonaws.services.kinesis.AmazonKinesisClient.invoke(AmazonKinesisClient.java:2498)
	at com.amazonaws.services.kinesis.AmazonKinesisClient.describeStream(AmazonKinesisClient.java:861)
	at com.amazonaws.services.kinesis.scaling.StreamScalingUtils.safeDescribeStream(StreamScalingUtils.java:122)
	at com.amazonaws.services.kinesis.scaling.StreamScalingUtils.getOpenShards(StreamScalingUtils.java:202)
	at com.amazonaws.services.kinesis.scaling.StreamScalingUtils.getOpenShardCount(StreamScalingUtils.java:145)
	at com.amazonaws.services.kinesis.scaling.StreamScaler.scaleUp(StreamScaler.java:127)
	at ScalingClient.run(ScalingClient.java:148)
	at ScalingClient.main(ScalingClient.java:196)
```

**Comment by IanMeyers** [comment]
Hello,

The utility uses the DefaultAWSCredentialsProviderChain (http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/auth/DefaultAWSCredentialsProviderChain.html), which uses the following order of precedence:

* Environment Variables - AWS_ACCESS_KEY_ID and AWS_SECRET_KEY
* Java System Properties - aws.accessKeyId and aws.secretKey
* Credential profiles file at the default location (~/.aws/credentials) shared by all AWS SDKs and the AWS CLI
* Instance profile credentials delivered through the Amazon EC2 metadata service

If you specify multiple profiles in the credentials file, then it appears that the ProfileCredentialsProvider (part of the default provider chain) will try each one (http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/auth/profile/ProfileCredentialsProvider.html).

So it sounds like rather than ~/.aws/config you need to create a 'credentials' file in the same directory in format as outlined at http://docs.aws.amazon.com/AWSSdkDocsJava/latest/DeveloperGuide/credentials.html.

Do let us know if that helps.

Ian

**Comment by lexicalunit** [comment]
After some searching I found this page http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/auth/ClasspathPropertiesFileCredentialsProvider.html which indicates "a file named AwsCredentials.properties on the classpath". However it does not indicate at all what the contents of the file should be. After some more googling I found some example `AwsCredentials.properties` files people had checked into github repos and it looks like the content of the file should be something like:

```
accessKey=omit
secretKey=omit
```

So I created that with my access tokens. Now I need to deal with the "on the classpath" part. After more googling I found out you can specify the classpath via the `-cp` argument to `java`, and that you can delimit paths using `;` tokens. So I tried this:

```
$ java -cp ".;KinesisScalingUtils.jar-complete.jar" -Dstream-name=mytest -Dscaling-action=scaleUp -Dcount=5 -Dregion=us-east-1 ScalingClient
Error: Could not find or load main class ScalingClient
```

So no more security token error, but now I can't even run the client.

**Comment by IanMeyers** [comment]
Hello - Yes, you have to explicitly name the properties file in order to have it be used - '.' wont pick it up :(

**Comment by lexicalunit** [comment]
Was able to get it working using `AWS_ACCESS_KEY_ID` and `AWS_SECRET_KEY`. Thanks for the very responsive help! :+1:

**Comment by tobiasmcnulty** [comment]
For anyone else who stumbles across this, it's `AWS_SECRET_ACCESS_KEY` not `AWS_SECRET_KEY`.

In my case, setting `AWS_PROFILE` did not work, but setting these variables did. Thanks for the find.

**Comment by ragowthaman** [comment]
Just in case......if someone visits here...

In my case when my account was suspended (due to non-payment of dues) I got the same errors. Visiting aws console helped to find that issue

**Comment by getvivekv** [comment]
Had the same problem, in my case, the User's permissions were revoked.

**Comment by jimiparekh** [comment]
Hello

**Comment by jimiparekh** [comment]
Hello,
I am trying to use a encryption key (using AWS Encryption SDK). I am getting the same error.
My key is like "**arn:aws:kms:us-east-1:XXXXXXXXXX**:_key/yyyyy-yyyy-yyyy-yyyy-yyyy"
I have set the environment variable 'AWS_ACCESS_KEY = arn:aws:kms:us-east-1:XXXXXXXXXX' and 'AWS_SECRET_KEY = key/yyyyy-yyyy-yyyy-yyyy-yyyy'. 

I am getting error: Exception in thread "main" com.amazonaws.services.kms.model.AWSKMSException: The
 security token included in the request is invalid. (Service: AWSKMS; Status Cod
e: 400; Error Code: UnrecognizedClientException; Request ID: 93d79101-e8c8-11e6-
af94-ed78adcea1db).

Can you please let me know what is the correct value for access_key and secret_key?

**Comment by IanMeyers** [comment]
The access key and secret key when used in this way come from the IAM User or Role that you have assumed in order to make calls to AWS Services. You can read more about Access and Secret keys at http://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_access-keys.html. These are very different from the Key Management Service keys, which are used for envelope encryption (among other things) - read more at https://aws.amazon.com/kms.

**Comment by mohammedghouse36** [comment]
Hi Everyone,

I am new to this aws thing i need some help how to authenthicate and create a project can some one please help me i struct intially. If some one boost up i can go further.

**Comment by mohammedghouse36** [comment]
How to work aws device farm using aws api. I have a java+TestNG project i want to create project by usng aws api can some help me on this. May be i kept at wrong place. please help me.

**Comment by ORESoftware** [comment]
isn't it AWS_SECRET_ACCESS_KEY not AWS_SECRET_KEY?

**Comment by dangtrinhnt-mmt** [comment]
I have to use AWS_ACCESS_KEY_ID & AWS_SECRET_ACCESS_KEY for the credentials to work.

**Comment by ms10596** [comment]
I have chosen a region that is not activated for my account, choosing another region solved the problem.

**Comment by ecochainadmin** [comment]
Based on the doc block in aws-sdk-java is best to use AWS_ACCESS_KEY_ID & AWS_SECRET_ACCESS_KEY 

https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/auth/DefaultAWSCredentialsProviderChain.java#L20

**Comment by andresisaza** [comment]
SOLUCIONADO!!! cuando estes en la linea de comando, y presiones aws configure, en la seccion que pregunta por la region, debes de poner la palabra local. y listo funciona.

**Comment by dillonharlessNHRMC** [comment]
In my case the issue was running powershell as an admin, so it was looking for my aws creds in my admin user's file. There's probably a better way to resolve it, but what worked quickly for me was recreating my .aws folder inside the root of my admin user.

**Comment by msalmandev** [comment]
Please verify AWS_ACCESS_KEY_ID and  AWS_SECRET_ACCESS_KEY.

**Comment by arsiaardalancanopy** [comment]
I followed the same steps, making sure all the credentials are updated AND that the `region` values in my `~/.aws/config` matches `~/.aws/credentials` but somehow the token would still be invalid. 
In my case, I had to `cd` into `~/.aws` and `rm` both `config` and `credentials` files. From there, running the command `aws configure` and providing the access id, secret access key, region, and output.

**Comment by kirvinod** [comment]
i tried all the above and still getting same issue.

**Comment by IanMeyers** [comment]
Can you share a bit more detail about how you have this deployed and how credentials are configured?

**Comment by kirvinod** [comment]
Hi Ian, 

Thank you for quick response, I know issue was close and its not directly related to kinesis utils. 

I am using serverless app using spring boot. Attached is complete log I am getting, 
[logs.txt](https://github.com/awslabs/amazon-kinesis-scaling-utils/files/5208926/logs.txt)

aws configs are fine, i can also see in logs that access key is correct.

`cat ~/.aws/config`

**[default]
region = eu-west-2
output = json**

`cat ~/.aws/credentials `

[default]
**aws_access_key_id = access
aws_secret_access_key = secret**

**Comment by daniol1618** [comment]
This is my advice to the ones that are having an error accessing the Secret manager resource access.

1. In the class that you are using to create client (The access to AWSSecretsManager) ;
 //Create a Secrets Manager client
        AWSSecretsManager client = AWSSecretsManagerClientBuilder.standard()
                .withRegion(region)
                .build();

        // We rethrow the exception by default.
        GetSecretValueRequest getSecretValueRequest = new GetSecretValueRequest().withSecretId(secretName);
        GetSecretValueResult getSecretValueResult = null;


        log.warn("SECRETOS **************  Region:" + region + " Secret Name:" + secretName);
        try {
            getSecretValueResult = client.getSecretValue(getSecretValueRequest);
        } catch (DecryptionFailureException e) {

**Comment by sharathbjgowda** [comment]
worked for me after setting "AWS_SESSION_TOKEN" env variable along with AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY since I had temporary access .

**Comment by avinash8083** [comment]
i changed the permission of file ,it started working for me .

**Comment by levellearning-admin** [comment]
if you use both AWS China and .com you might also need to specify the region with your command by doing
```
--region cn-northwest-1 
--region cn-north-1
```
depending on your needs 

(I apologize for necro)
