### ISSUE TITLE
How to scale a specific Shard as mentioned in the README file?

### ISSUE THREAD

**Issue by ravi2274** [awslabs/amazon-kinesis-scaling-utils#57]
As mentioned in the document, I tried up-scaling a specific shard with a factor of 3, it prints 'Scaling Operation Complete', and a Null Pointer Exception is thrown. Exception Stack -

Exception in thread "main" java.lang.NullPointerException
        at ScalingClient.run(ScalingClient.java:204)
        at ScalingClient.main(ScalingClient.java:220)

After going through the codebase, I can see some methods for Scaling a specific Shard but it hasn't been completely implemented yet! Is this feature available in a beta version that I have missed. I am using KinesisScalingUtils-.9.5.4-complete.jar

**Comment by IanMeyers** [comment]
This is only available from the scaling client. For example:

```java -cp dist/KinesisScalingUtils-complete.jar -Dstream-name=MyStream -Dscaling-action=scaleUp -Dcount=3 -Dshard-id=shard-0000000000 -Dregion=eu-west-1 ScalingClient```
