### ISSUE TITLE
How do I use a non-default profile from ~/.aws/credentials?

### ISSUE THREAD

**Issue by foragerr** [awslabs/amazon-kinesis-scaling-utils#59]
Hi, ref this comment: https://github.com/awslabs/amazon-kinesis-scaling-utils/issues/5#issuecomment-87037905

Running something like `java -cp dist/KinesisScalingUtils-complete.jar -Dstream-name=MyStream -Dscaling-action=report -Dregion=eu-west-1 ScalingClient` is using my [default] profile from the credentials file. How do I specify the use of a different profile?

To draw a parallel aws cli uses the `--profile` flag to use a named profile.

**Comment by IanMeyers** [comment]
Please consult this guide for information on how to work with credentials: https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/credentials.html
