### ISSUE TITLE
Is there any way to monitoring the monitor? 

### ISSUE THREAD

**Issue by igorromcy** [awslabs/amazon-kinesis-scaling-utils#66]
There is any way to know if I will get some error starting a service? (I want to make sure that monitor is monitoring, periodically)
This king of error:
` java.io.IOException: Unable to load local file from /config/autoscaling.json`

I tried to make a curl to: 
`curl -I -X GET http://localhost:8080/KinesisAutoscaling-.9.5.2/index.html`

but this is the apache status (ever is 200 for me)

**Comment by IanMeyers** [comment]
Yes, this is an issue in that not being able to startup isn't a fatal for the tomcat application. Will look into it.

**Comment by IanMeyers** [comment]
Version .9.5.9 System will now abort with a fatal error on config load or other monitor startup issues unless `suppress-abort-on-fatal` is set. This fatal means you'll get a 503 from the web server root if there's a startup problem.
