### ISSUE TITLE
Scaling fails intermittently

### ISSUE THREAD

**Issue by ankur2104** [awslabs/amazon-kinesis-scaling-utils#78]
I tried manual scaling using the jar and at times shard doesn't scale fully. For example I scaled up from 32 to 46 and it stopped at 41 and the shard status turned active. But this is an intermittent issue and if I try again it does scale up to that number too.

**Comment by IanMeyers** [comment]
You can always retry and the system will only pick up where it left off. Please paste an error trace from the Beanstalk application and we can try and diagnose further.
