### ISSUE TITLE
ScaleDown action keep adding the number of shards.

### ISSUE THREAD

**Issue by ystepanovy** [awslabs/amazon-kinesis-scaling-utils#9]
Tested application and noticed following issues:
1. On quiet stream the application keep adding shards. I thought there will be some dependency on the throughput.
2. scaleDown works the same way as scaleUp. I ended up with 100 shards in 20 min.
3. Web instance of the application is very scripted... some additional light would be helpful.

**Comment by IanMeyers** [comment]
Hello,

Sorry to hear you are having this issue, and this isn't something we've seen in the past. Can you please attach the catalina.out logfile from your Elastic Beanstalk environment, as well as the configuration file? Also, I'm not sure I understand what you meant in point 3.

Thx,

Ian

**Comment by IanMeyers** [comment]
Closed due to inactivity.
