### ISSUE TITLE
Missing dist files for .9.7.0

### ISSUE THREAD

**Issue by sshivananda** [awslabs/amazon-kinesis-scaling-utils#93]
The [dist folder](https://github.com/awslabs/amazon-kinesis-scaling-utils/tree/master/dist) does not contain the war/jar files for  v .9.7.0.

Because of this the [link](https://github.com/awslabs/amazon-kinesis-scaling-utils/blob/master/dist/KinesisAutoscaling-.9.7.0.war) in the README is broken as well.

**Comment by IanMeyers** [comment]
This is fixed
